on: 
  push:
    paths: ['**.R', '**.qml', '**.po', '**.yml']
 
  pull_request:
    paths: ['**.R', '**.qml', '**.po', '**.yml']
  
  workflow_dispatch:

name: i18n-check

jobs:
  i18n-check:
    uses: jasp-stats/jasp-actions/.github/workflows/i18nCheck.yml@master
