on:
  schedule:
    - cron:  '30 2 * * 6'
    
  workflow_dispatch:

name: generate-translations

jobs:
  generate-translations:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_KEY }}
      WEBLATE_KEY: ${{ secrets.WEBLATE_KEY }}
      QML_REPO: jaspmetaanalysis-qml
      R_REPO: jaspmetaanalysis-r

    steps:
      - uses: jasp-stats/jasp-actions/wlcLock@master
      
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_KEY }}

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: "4.0.5"

      - uses: jasp-stats/jasp-actions/translations@master
